name: Update types and release
on:
  push:
    paths:
      - release-versions/*
  workflow_dispatch:
jobs:
  generate-types:
    name: Generate types from latest tagged version
    runs-on: ubuntu-latest
    outputs:
      commit-changes: ${{ steps.git-check.outputs.modified }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: types
      - name: Set up git identity
        run: |
          git config --global user.name 'David Roizenman'
          git config --global user.email 'david@hmnd.io@users.noreply.github.com'
      - run: |
          echo "current_tag=$(cat types/release-versions/latest.txt | head -n 1)" >> $GITHUB_ENV
      - name: Checkout webpack-dev-server repo
        uses: actions/checkout@v2
        with:
          repository: webpack/webpack-dev-server
          path: upstream
          ref: ${{ env.current_tag }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm i -g quicktype
          npm i -g hygen
      - name: Generate types
        run: |
          npx quicktype upstream/lib/options.json -s schema --top-level Configuration -o index.gen.d.ts --just-types
      - name: Remove old types
        run: rm -f types/index.d.ts
      - name: Namespace type
        working-directory: ./types
        run: |
          npx hygen typesgen new --devServerTypes="$(<../index.gen.d.ts)"
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
  update-repo-types:
    name: Commit updated types
    needs: [generate-types]
    if: needs.generate-types.outputs.commit-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit updated types
        run: |
          git commit -am "chore: update types"
      - name: Update package version
        run: |
          npm version "${{ env.current_tag }}" --allow-same-version
          npm install
      - name: Commit changes
        run: |
          git commit -am "${{ env.current_tag }}"
          git tag -a "${{ env.current_tag }}" -m "${{ env.current_tag }}"
          git push --follow-tags
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
